# Generated by Django 5.1.7 on 2025-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.CharField(blank=True, max_length=5000, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('popularity', models.CharField(blank=True, max_length=50, null=True)),
                ('vote_average', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_count', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
